spring.application.name=locadora
spring.datasource.url=jdbc:mysql://localhost:3306/locadora?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
 
pring.jpa.show-sql=false
spring.mvc.hiddenmethod.filter.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false
server.port=8080